### ISSUE TITLE
Issues training a model

### ISSUE THREAD

**Issue by paru16** [haotianteng/Chiron#38]
Hello,

I've been having trouble training a model with the latest git release. I've resquiggled my training set and extracted the signal/label files without any issue. However, when I try to run chiron_train.py, I end up with the following error:
```
python new_chiron/chiron/chiron/chiron_train.py -i $HOME/signal -o $HOME/log -m test

Traceback (most recent call last):
  File "/home/new_chiron/chiron/chiron/chiron_train.py", line 184, in <module>
    run(hparam.HParams(**args.__dict__)) 
  File "/home/new_chiron/chiron/chiron/chiron_train.py", line 125, in run
    train(hparam)
  File "/home/new_chiron/chiron/chiron/chiron_train.py", line 75, in train
    for_valid=False)
  File "/stornext/HPCScratch/home/new_chiron/chiron/chiron/chiron_queue_input.py", line 130, in inputs
    filename_queue = tf.train.string_input_producer(filenames)
  File "/home/.conda/envs/chiron_basecaller_env/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 217, in string_input_producer
    raise ValueError(not_null_err)
ValueError: string_input_producer requires a non-null input tensor
```

I tried running chiron_train_rcnn.py too, but that failed with the following error:
```
python new_chiron/chiron/chiron/chiron_rcnn_train.py -i $HOME/signal -o $HOME/log -m test

(200, 1, 400, 1)
Traceback (most recent call last):
  File "/home/new_chiron/chiron/chiron/chiron_rcnn_train.py", line 137, in <module>
    run(args)
  File "/home/new_chiron/chiron/chiron/chiron_rcnn_train.py", line 108, in run
    train()
  File "/home/new_chiron/chiron/chiron/chiron_rcnn_train.py", line 49, in train
    opt = model.train_step(ctc_loss, FLAGS.step_rate, global_step=global_step)
AttributeError: 'module' object has no attribute 'train_step'

```
Any advice would be appreciated! Thanks.

**Comment by haotianteng** [comment]
Use chiron.utils.raw to transfer fast5 files into tfrecord and then train with chiron_rcnn_train.py
or chiron.utils.file_batch to transfer the fast5 files into file batch and then train with chiron_train.py. If you use file_batch.py, the segment length has to be same when using chiron_train.py
