### ISSUE TITLE
Issue with chiron_train.py

### ISSUE THREAD

**Issue by paru16** [haotianteng/Chiron#39]
Hello,

Thanks so much for the advice before! I've used file_batch.py to transfer my training set of fast5 files into batch, but I'm still running into issues with chiron_train.py (the segment length is set to 512 in both cases). 

```
python chiron_train.py --data-dir new_fast5 --log-dir model_update --model-name bb12_new

Filling queue with 500000 signals before starting to train. This will take some time.(200, 1, 512, 1)
Traceback (most recent call last):
  File "chiron_train.py", line 184, in <module>
    run(hparam.HParams(**args.__dict__)) 
  File "chiron_train.py", line 125, in run
    train(hparam)
  File "chiron_train.py", line 81, in train
    step = opt.minimize(loss,global_step = global_step)
NameError: global name 'loss' is not defined
```

**Comment by haotianteng** [comment]
I guess it's a typo during reformating, from a simple look change the "loss" to "ctc_loss" should do the job.
