### ISSUE TITLE
AttributeError: 'tqdm' object has no attribute 'pos'

### ISSUE THREAD

**Issue by rbutleriii** [haotianteng/Chiron#59]
Environment: Fedora23 x64 , pyenv python environment -> 2.7.15.
Installed via pip:
`pip install chiron`
`pip install tensorflow`
got the following Traceback:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/rbutler/.pyenv/versions/2.7.15/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/rbutler/.pyenv/versions/2.7.15/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/rbutler/.pyenv/versions/2.7.15/lib/python2.7/site-packages/chiron/chiron_eval.py", line 267, in run_listener
    worker_fn()
  File "/home/rbutler/.pyenv/versions/2.7.15/lib/python2.7/site-packages/chiron/chiron_eval.py", line 239, in worker_fn
    for name in tqdm(file_list,desc = "Logits inferencing.",position = 0):
  File "/home/rbutler/.pyenv/versions/2.7.15/lib/python2.7/site-packages/tqdm/_tqdm.py", line 990, in __iter__
    self.close()
  File "/home/rbutler/.pyenv/versions/2.7.15/lib/python2.7/site-packages/tqdm/_tqdm.py", line 1087, in close
    self._decr_instances(self)
  File "/home/rbutler/.pyenv/versions/2.7.15/lib/python2.7/site-packages/tqdm/_tqdm.py", line 446, in _decr_instances
    if inst.pos > abs(instance.pos):
AttributeError: 'tqdm' object has no attribute 'pos'
```
bare install of python, pip list:
```
Package           Version
----------------- ---------
absl-py           0.2.2
astor             0.6.2
backports.weakref 1.0.post1
bleach            1.5.0
chiron            0.4
enum34            1.1.6
funcsigs          1.0.2
futures           3.2.0
gast              0.2.0
grpcio            1.12.1
h5py              2.8.0
html5lib          0.9999999
mappy             2.11
Markdown          2.6.11
mock              2.0.0
numpy             1.14.5
pandas            0.23.1
patsy             0.5.0
pbr               4.0.4
pip               10.0.1
protobuf          3.6.0
python-dateutil   2.7.3
pytz              2018.4
scipy             1.1.0
setuptools        39.0.1
six               1.11.0
statsmodels       0.9.0
tensorboard       1.8.0
tensorflow        1.8.0
termcolor         1.1.0
tqdm              4.23.4
Werkzeug          0.14.1
wheel             0.31.1
```

**Comment by haotianteng** [comment]
can you try to install the newest version of tqdm

**Comment by rbutleriii** [comment]
pulled dev version from github: 
`pip install -e git+https://github.com/tqdm/tqdm.git@master#egg=tqdm`
Perhaps a momentary hiccup, but pip version of tqdm doesn't have the latest changes.
Now no longer has error. Now exits after scanning with the following:
```
Subdirectory processing:: 1it [00:05,  5.42s/it]
2018-06-24 16:33:45.873239: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: FMA
chiron_recall/2016-04-04_CJ5:00, ?it/s]
Real time:2.250 Systime:0.213 Usertime:2.229
```
