### ISSUE TITLE
appear at different stage: AttributeError: 'tqdm' object has no attribute 'pos' 

### ISSUE THREAD

**Issue by Huanle** [haotianteng/Chiron#64]
Hi Haotian,

I ran into the following error and it seems to pop up at different time during multiple trials of 

```
$ chiron call -i 736688-175.fast5/ -o ./ -m ~/h.liu/scripts/chiron/chiron/model/DNA_default/ -b 4  -t 6

/home/913/hl0222/.local/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Subdirectory processing:: 1it [01:04, 64.80s/it]
2018-07-18 16:32:16.327732: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-18 16:32:16.563024: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:84:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-07-18 16:32:16.731698: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 1 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:85:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-07-18 16:32:16.732188: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Device peer to peer matrix
2018-07-18 16:32:16.732255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1051] DMA: 0 1
2018-07-18 16:32:16.732287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 0:   Y Y
2018-07-18 16:32:16.732309: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 1:   Y Y
2018-07-18 16:32:16.732338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:84:00.0, compute capability: 3.7)
2018-07-18 16:32:16.732363: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:1) -> (device: 1, name: Tesla K80, pci bus id: 0000:85:00.0, compute capability: 3.7)
Logits inferencing.:   0%|          | 4/3996 [05:31<91:56:43, 82.92s/it]                  Exception
Logits inferencing:   0%|          | 0/83 [00:00<?, ?it/s] in <bound method tqdm.__del__ of CTC decoding.:   0%|          | 3/3996 [05:31<122:37:42, 110.56s/it]> ignored7, 27.79s/it]Traceback (most recent call last):
  File "/home/913/hl0222/.local/bin/chiron", line 11, in <module>]decoded_q=0, logits_q=0]
    load_entry_point('chiron==0.4', 'console_scripts', 'chiron')()
  File "/home/913/hl0222/.local/lib/python2.7/site-packages/chiron/entry.py", line 91, in main
    args.func(args)
  File "/home/913/hl0222/.local/lib/python2.7/site-packages/chiron/entry.py", line 26, in evaluation
    chiron_eval.run(args)
  File "/home/913/hl0222/.local/lib/python2.7/site-packages/chiron/chiron_eval.py", line 398, in run
    time_dict = unix_time(evaluation)
  File "/home/913/hl0222/.local/lib/python2.7/site-packages/chiron/utils/unix_time.py", line 21, in unix_time
    function(*args, **kwargs)
  File "/home/913/hl0222/.local/lib/python2.7/site-packages/chiron/chiron_eval.py", line 307, in evaluation
    break
  File "/home/913/hl0222/.local/lib/python2.7/site-packages/tqdm-4.23.4-py2.7.egg/tqdm/_tqdm.py", line 878, in __exit__
    self.close()
  File "/home/913/hl0222/.local/lib/python2.7/site-packages/tqdm-4.23.4-py2.7.egg/tqdm/_tqdm.py", line 1087, in close
    self._decr_instances(self)
  File "/home/913/hl0222/.local/lib/python2.7/site-packages/tqdm-4.23.4-py2.7.egg/tqdm/_tqdm.py", line 446, in _decr_instances
    if inst.pos > abs(instance.pos):
AttributeError: 'tqdm' object has no attribute 'pos'
```

Although it seems to be tqdm specific issue. I have no clue to fix it.
Hope you can help me sort it out.

Thanks a lot.

Huanlee

**Comment by haotianteng** [comment]
Update to the newest version of tqdm should solve the problem.

**Comment by Huanle** [comment]
@haotianteng 

thanks a lot.

```
$ pip2.7 install  --user --upgrade tqdm
Requirement already up-to-date: tqdm in /home/913/hl0222/.local/lib/python2.7/site-packages/tqdm-4.23.4-py2.7.egg
```
It lasted longer this time and produced more fastq files  before corruption.

```
$chiron call -i 736688-175.fast5/ -o call.2 -m ~/h.liu/scripts/chiron/chiron/model/DNA_default/ -t 2 -e call_2
/home/913/hl0222/.local/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
('model_default_path', '/home/913/hl0222/.local/lib/python2.7/site-packages/chiron/model/DNA_default')
Subdirectory processing:: 1it [01:25, 85.75s/it]
2018-07-24 10:14:03.721015: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-24 10:14:03.984393: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:09:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-07-24 10:14:04.166518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 1 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:0a:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-07-24 10:14:04.167016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Device peer to peer matrix
2018-07-24 10:14:04.167096: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1051] DMA: 0 1
2018-07-24 10:14:04.167131: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 0:   Y Y
2018-07-24 10:14:04.167155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 1:   Y Y
2018-07-24 10:14:04.167196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:09:00.0, compute capability: 3.7)
2018-07-24 10:14:04.167231: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:1) -> (device: 1, name: Tesla K80, pci bus id: 0000:0a:00.0, compute capability: 3.7)
Logits inferencing.:  60%|##############################1                   | 2410/3996 [2:10:00<1:25:33,  3.24s/it^[[Bits inferencing:  50%|##############################5                              | 1/2 [00:01<00:01,  1.50s/it]
Logits inferencing.:  77%|#######################################8            | 3064/3996 [2:44:06<49:55,  3.21s/it]
Logits inferencing:   0%|                                                                     | 0/1 [00:00<?, ?it/s]
Output: 100%|########################################################################| 1/1 [00:00<00:00, 593.42it/s]



Logits inferencing.:  90%|##############################################6     | 3583/3996 [3:12:29<22:11,  3.22s/it]
Logits inferencing:   0%|                                                                     | 0/1 [00:00<?, ?it/s]
Logits inferencing.: 100%|###################################################9| 3990/3996 [3:33:33<00:19,  3.21s/it^Logits inferencing.: 100%|###################################################9| 3991/3996 [3:33:37<00:16,  3.21s/it]
Logits inferencing:   0%|                                                                     | 0/2 [00:00<?, ?it/s]
Exception KeyError: KeyError(<weakref at 0x7f1742d7f578; to 'tqdm' at 0x7f1742f81cd0>,) in <bound method tqdm.__del__ of CTC decoding.:   1%|3                                                      | 24/3996 [3:33:57<590:11:22, 534.91s/it]> ignored
call.2
Real time:12842.225 Systime:4374.182 Usertime:20142.904

```

**Comment by haotianteng** [comment]
Can you check if it's finished? It looks like Chiron has already finished
the basecalling.

**Comment by Huanle** [comment]
@haotianteng 

there are 3996 *signal files in raw/ folder.
last file in result/ folder corresponds to the 3029th file in /raw folder. 
So it seems bascalling is done though it is unbelievable that only 27 reads were basecalled.
I will double check it. But still the error message is confusing.

**Comment by haotianteng** [comment]
It's a tqdm error in Python3 under multiple threadings [https://github.com/tqdm/tqdm/issues/571](url)

**Comment by SrinikhilReddy** [comment]
@Huanle Were you able to avoid this issue anyway? Facing the same.

**Comment by haotianteng** [comment]
It's problem with tqdm conflict with multiple threading, short solution would be roll back to Chiron-0.3 and Tensorflow 1.0.1, I will remove tqdm until it is fixed.

**Comment by haotianteng** [comment]
Hi after some check I found the tqdm call inside a thread worker cause the breakdown, so I remove the this count.

**Comment by kehey** [comment]
Hi @haotianteng ,

I seem to be still running into the problem. I updated tqdm to version 4.24.0 and updated chiron with
`pip install --upgrade git+https://github.com/haotianteng/Chiron.git`

I verified that the changes are by the fact that I see the changes you made in 4.1 when I check the files manually:

```bash
$ sed -n 238,280p /data/workspace/personal/anaconda_envs_path/chiron_27_v2/lib/python2.7/site-packages/chiron/chiron_eval.py
        def worker_fn():
            for name in file_list:
                if not name.endswith('.signal'):
                    continue
                input_path = os.path.join(file_dir, name)
                eval_data = read_data_for_eval(input_path, FLAGS.start,
                                               seg_length=FLAGS.segment_len,
                                               step=FLAGS.jump)
                reads_n = eval_data.reads_n
                for i in trange(0, reads_n, FLAGS.batch_size,desc = "Logits inferencing",position = 2):
                    batch_x, seq_len, _ = eval_data.next_batch(
                        FLAGS.batch_size, shuffle=False, sig_norm=False)
                    batch_x = np.pad(
                        batch_x, ((0, FLAGS.batch_size - len(batch_x)), (0, 0)), mode='constant')
                    seq_len = np.pad(
                        seq_len, ((0, FLAGS.batch_size - len(seq_len))), mode='constant')
                    feed_dict = {
                        x: batch_x,
                        seq_length: seq_len,
                        training: False,
                        logits_index:i,
                        logits_fname: name,
                    }
                    sess.run(logits_enqueue,feed_dict=feed_dict)
            sess.run(logits_queue_close)
        def run_listener(write_lock):
            # This function is used to solve the error when tqdm is used inside thread
            # https://github.com/tqdm/tqdm/issues/323
            tqdm.set_lock(write_lock)
            worker_fn()
        write_lock = threading.Lock()
        worker = threading.Thread(target=run_listener,args=(write_lock,) )
        worker.setDaemon(True)
        worker.start()

        val = defaultdict(dict)  # We could read vals out of order, that's why it's a dict
        for name in tqdm(file_list, desc="Total process",position = 1):
            start_time = time.time()
            if not name.endswith('.signal'):
                continue
            file_pre = os.path.splitext(name)[0]
            input_path = os.path.join(file_dir, name)
            if FLAGS.mode == 'rna':

```

I still get the error below:

```bash
^Mctc decoding: 100%|#########9| 4000/4013 [00:11<00:00, 334.68it/s, decoded_q=0, logits_q=0]^[[A^[[A^[[A

^MLogits inferencing: 100%|##########| 21/21 [00:12<00:00,  1.67it/s]^[[A^[[A

^[[A^[[AException

KeyError^MLogits inferencing:   0%|          | 0/67 [00:00<?, ?it/s]: ^[[A^[[AKeyError(<weakref at 0x7fca64740aa0; to 'tqdm' at 0x7fca64746d90>,) in <bound method tqdm.__del__ of Total process:   3%|2         | 55/1999 [09:41<5:42:47, 10.58s/it]> ignored


^MLogits inferencing:   1%|1         | 1/67 [00:00<00:36,  1.79it/s]^[[A^[[A

^MLogits inferencing:   3%|2         | 2/67 [00:01<00:37,  1.73it/s]^[[A^[[A

^MLogits inferencing:   4%|4         | 3/67 [00:01<00:37,  1.71it/s]^[[A^[[A

^MLogits inferencing:   6%|5         | 4/67 [00:02<00:36,  1.70it/s]^[[A^[[A

^MLogits inferencing:   7%|7         | 5/67 [00:02<00:36,  1.70it/s]^[[A^[[A

^MLogits inferencing:   9%|8         | 6/67 [00:03<00:36,  1.69it/s]^[[A^[[ATraceback (most recent call last):
  File "/data/workspace/ggbtg/personal/anaconda_envs_path/chiron_27_v2/lib/python2.7/site-packages/chiron/entry.py", line 99, in <module>
    main()
  File "/data/workspace/ggbtg/personal/anaconda_envs_path/chiron_27_v2/lib/python2.7/site-packages/chiron/entry.py", line 91, in main
    args.func(args)
  File "/data/workspace/ggbtg/personal/anaconda_envs_path/chiron_27_v2/lib/python2.7/site-packages/chiron/entry.py", line 26, in evaluation
    chiron_eval.run(args)
  File "/data/workspace/ggbtg/personal/anaconda_envs_path/chiron_27_v2/lib/python2.7/site-packages/chiron/chiron_eval.py", line 398, in run
    time_dict = unix_time(evaluation)
  File "/data/workspace/ggbtg/personal/anaconda_envs_path/chiron_27_v2/lib/python2.7/site-packages/chiron/utils/unix_time.py", line 21, in unix_time
    function(*args, **kwargs)
  File "/data/workspace/ggbtg/personal/anaconda_envs_path/chiron_27_v2/lib/python2.7/site-packages/chiron/chiron_eval.py", line 307, in evaluation
    break
  File "/data/workspace/ggbtg/personal/anaconda_envs_path/chiron_27_v2/lib/python2.7/site-packages/tqdm/_tqdm.py", line 879, in __exit__
    self.close()
  File "/data/workspace/ggbtg/personal/anaconda_envs_path/chiron_27_v2/lib/python2.7/site-packages/tqdm/_tqdm.py", line 1088, in close
    self._decr_instances(self)
  File "/data/workspace/ggbtg/personal/anaconda_envs_path/chiron_27_v2/lib/python2.7/site-packages/tqdm/_tqdm.py", line 446, in _decr_instances
    if inst.pos > abs(instance.pos):
AttributeError: 'tqdm' object has no attribute 'pos'

```

**Comment by SrinikhilReddy** [comment]
@haotianteng Thanks a lot for the quick reply. However, the issue still remains. 

Recreating the issue:

1. Model used: Default DNA model
2. Fast5 files used: https://data.genomicsresearch.org/Projects/train_set_all/pass.tar.gz

I have removed all instances of tqdm reference and ran the code. Still the issue reamins.

**Comment by haotianteng** [comment]
@SrinikhilReddy 
I runned on the test dataset and it didn't give me any problem, how did you run the command?
Could you upload the code and the error?

**Comment by haotianteng** [comment]
@SrinikhilReddy @kehey @Huanle 
Could you try git pull the latest Chiron,
and set this:
`export HDF5_USE_FILE_LOCKING=FALSE`

And tell me if there is still any problem. I have test on my local dataset with both py2 and py3 and there is no problem now.

**Comment by kehey** [comment]
Done. The stderr now ends with:

```
AttributeError: 'tqdm' object has no attribute 'pos'
2018-08-20 14:42:01.384213: E tensorflow/stream_executor/cuda/cuda_driver.cc:1099] could not wait stream on event: CUDA_ERROR_DEINITIALIZED
2018-08-20 14:42:01.384286: E tensorflow/stream_executor/cuda/cuda_blas.cc:654] failed to run cuBLAS routine cublasSgemm_v2: CUBLAS_STATUS_EXECUTION_FAILED
2018-08-20 14:42:01.384251: E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_DEINITIALIZED
2018-08-20 14:42:01.384343: E tensorflow/stream_executor/cuda/cuda_blas.cc:654] failed to run cuBLAS routine cublasSgemm_v2: CUBLAS_STATUS_EXECUTION_FAILED
2018-08-20 14:42:01.384343: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:208] Unexpected Event status: 1
2018-08-20 14:42:01.408437: I tensorflow/stream_executor/stream.cc:4737] stream 0x558c2ef80570 did not memcpy host-to-device; source: 0x7f90f1603700
``

**Comment by kehey** [comment]
No problem. Thanks for the guidance so far. 

The way I launch it is:

```
python $CHIRON/entry.py call -i $IN \
                             -o $OUT \
                             -m $CHIRON/model/DNA_default/ \
                             -b 200 \
                             -l 400 \
                             -t 4 \
                             --beam 0 \
                             --mode DNA \
                             1> $OUT/stdout \
                             2> $OUT/stderr
```

I'll see whether I can debug myself into the tqdm error loop.

**Comment by haotianteng** [comment]
I write a progress bar myself and remove the use of tqdm in the chiron_eval module, now it will not cover the true error, please have a try and tell me if solves your problem.
