### ISSUE TITLE
Error with basecalling with non-default model

### ISSUE THREAD

**Issue by damientully** [haotianteng/Chiron#79]
Hello,

I have been training Chiron v.0.4.2 with a custom dataset I’ve created a model using chiron_rcnn_train.py (without any apparent issues), but basecalling against this model has been failing with the following error. I have trained the model with 20000 steps and attached the log output.  In addition, I have modified the checkpoint file to: model_checkpoint_path: "final.ckpt-20000" . The command that I am using to basecall with the non-default model is `chiron call -i /n/scratch2/dct7/Run12_raw_reads/1 -o test_model --model /home/dct7/chiron/lib/python2.7/site-packages/chiron/model/HIV
`
Any suggestions?

Thanks,
Damien
[training-30411904.txt](https://github.com/haotianteng/Chiron/files/2724716/training-30411904.txt)

`WARNING:tensorflow:From /home/dct7/chiron/lib/python2.7/site-packages/chiron/chiron_eval.py:399: __init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/dct7/chiron/lib/python2.7/site-packages/chiron/chiron_eval.py:400: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
2019-01-03 07:10:12.480454: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-03 07:10:26.695457: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:08:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2019-01-03 07:10:26.933233: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 1 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:09:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2019-01-03 07:10:26.933596: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1
2019-01-03 07:10:27.621913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-03 07:10:27.621946: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1 
2019-01-03 07:10:27.621951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N Y 
2019-01-03 07:10:27.621954: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   Y N 
2019-01-03 07:10:27.622517: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10757 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:08:00.0, compute capability: 3.7)
2019-01-03 07:10:27.623001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10757 MB memory) -> physical GPU (device: 1, name: Tesla K80, pci bus id: 0000:09:00.0, compute capability: 3.7)
WARNING:tensorflow:From /home/dct7/chiron/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py:804: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:ParseError: 1:24 : Expected string but found: '\xe2'
WARNING:tensorflow:/home/dct7/chiron/lib/python2.7/site-packages/chiron/model/HIV/checkpoint: Checkpoint ignored
2019-01-03 07:12:27.951255: W tensorflow/core/kernels/queue_base.cc:285] _1_fifo_queue: Skipping cancelled dequeue attempt with queue not closed
2019-01-03 07:12:27.951701: W tensorflow/core/kernels/queue_base.cc:285] _1_fifo_queue: Skipping cancelled dequeue attempt with queue not closed
2019-01-03 07:12:27.954637: W tensorflow/core/kernels/queue_base.cc:285] _1_fifo_queue: Skipping cancelled dequeue attempt with queue not closed
2019-01-03 07:12:27.954767: W tensorflow/core/kernels/queue_base.cc:285] _1_fifo_queue: Skipping cancelled dequeue attempt with queue not closed
2019-01-03 07:12:27.954779: W tensorflow/core/kernels/queue_base.cc:285] _1_fifo_queue: Skipping cancelled dequeue attempt with queue not closed
2019-01-03 07:12:27.955063: W tensorflow/core/kernels/queue_base.cc:285] _1_fifo_queue: Skipping cancelled dequeue attempt with queue not closed
('model_default_path', '/home/dct7/chiron/lib/python2.7/site-packages/chiron/model/DNA_default')
CNN output has the segment length 300, and 256 channels
Traceback (most recent call last):
  File "/home/dct7/chiron/bin/chiron", line 11, in <module>
    sys.exit(main())
  File "/home/dct7/chiron/lib/python2.7/site-packages/chiron/entry.py", line 91, in main
    args.func(args)
  File "/home/dct7/chiron/lib/python2.7/site-packages/chiron/entry.py", line 26, in evaluation
    chiron_eval.run(args)
  File "/home/dct7/chiron/lib/python2.7/site-packages/chiron/chiron_eval.py", line 408, in run
    time_dict = unix_time(evaluation)
  File "/home/dct7/chiron/lib/python2.7/site-packages/chiron/utils/unix_time.py", line 21, in unix_time
    function(*args, **kwargs)
  File "/home/dct7/chiron/lib/python2.7/site-packages/chiron/chiron_eval.py", line 233, in evaluation
    saver.restore(sess, tf.train.latest_checkpoint(FLAGS.model))
  File "/home/dct7/chiron/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1534, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.`

**Comment by haotianteng** [comment]
Can you print out your checkpoint file in your model log folder?
The error shows that the path of the file can not be found

**Comment by damientully** [comment]
Hi @haotianteng 

`model_checkpoint_path: “model.ckpt-20000”
`

Thanks.

**Comment by haotianteng** [comment]
The error report shows that the model is not found in the given path.
Can you double check if the path is correct? And are the model.json and all the model save file in the model folder?

**Comment by damientully** [comment]
Thanks for the reply.

`~/chiron/lib/python2.7/site-packages/chiron/model/HIV$ pwd`
`/home/dct7/chiron/lib/python2.7/site-packages/chiron/model/HIV`

and I have the following files in there
checkpoint                           
model.ckpt-20000.index 
model.json
model.ckpt-20000.data-00000-of-00001  
model.ckpt-20000.meta

Am I missing anything?

**Comment by haotianteng** [comment]
Could you add a printout after the Line233 in chiron_eval.py
print(tf.train.latest_checkpoint(FLAGS.model)) to see if the model has been found?
And is there any file in the test_model/raw folder? There should be the same number of signal files as the original fast5 files.

Also could you try running chiron_eval directly to avoid any potential bug in the entry module.
From the same folder:
python chiron_eval.py -i test_model/raw -o test_model/ --model /home/dct7/chiron/lib/python2.7/site-packages/chiron/model/HIV

**Comment by damientully** [comment]
That helped figure out the problem. As the checkpoint file for my model was not being printed out in its entirety so copying the default DNA model checkpoint file and editing it to my model worked. Although my model (solely trained on viral data) is in fact on average 5% worse in terms of identity compared to the default DNA model which is surprising to me as I expected to be higher! 

Is it possible to use the v0.3 model with v0.4 as the v0.4. model is re-trained on human reads? But I didn't see a model.json file with v0.3 so not sure if it is compatible. 

Many thanks

**Comment by haotianteng** [comment]
You can use Chiron-v0.3 with tf-1.0.1, the DNA default model is totally fine. I think from the print out of your training record, your model is not totally converged. And I think training from scratch is not a good idea, as we use a huge amount of data training the new DNA-default model. What I suggest is to retrain the DNA-default model with your data. which may give a better result.
For retraining, it's simple, just add --retrain flag, and remove the --configure flag, as the model will automatically load the DNA_default model configuration from the model.json file.
