### ISSUE TITLE
Source installation instructions not working

### ISSUE THREAD

**Issue by jackwadden** [haotianteng/Chiron#87]
**Describe the bug**
Source installation instructions and example script do not run to completion on Ubuntu 16.04 LTS 

**To Reproduce**
To install Chiron and run the example script, I'm following the steps below from the README (and some supplements). Once I think I have Chiron installed correctly, I'm running using the exact example command from the README (i.e. python chiron/entry.py call -i chiron/example_folder/ -o <output_folder> -m chiron/model/DNA_default -b 1100 -l 400 -j 40 --beam 30 --mode dna)

1. git clone https://github.com/haotianteng/Chiron
2. export PYTHONPATH=<path to chiron>:$PYTHONPATH
3. pip install -r requirements.txt (run command; complains about no module named packaging)
4. pip install packaging (run command; complains about no module Bio)
5. pip install biopython (run command; compains about numpy installation being corrupted)
6 pip install -r requirements.txt (run command; runs, but eventually fails)

Chiron then runs but eventually fails with the following error:

Traceback (most recent call last):
  File "chiron/entry.py", line 154, in <module>
    main()
  File "chiron/entry.py", line 146, in main
    args.func(args)
  File "chiron/entry.py", line 40, in evaluation
    chiron_eval.run(args)
  File "/home/jack/r/Chiron/chiron/chiron_eval.py", line 514, in run
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 250, in _run
    coord.request_stop(e)
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 211, in request_stop
    six.reraise(*sys.exc_info())
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 234, in _run
    sess.run(enqueue_op)
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
CancelledError: Dequeue operation was cancelled
	 [[Node: fifo_queue_Dequeue = QueueDequeueV2[component_types=[DT_FLOAT, DT_STRING, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue)]]

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python: 2.7.12

Am I doing anything wrong? If not, could someone sanity check installation from source and help me get the examples running?

Thanks in advance!

-Jack

**Comment by haotianteng** [comment]
Hi Jack,
Please do the following:

```
git clone https://github.com/haotianteng/Chiron.git
cd Chiron
python setup.py install
```
Then you can choose to install Tensorflow, or Tensorflow-gpu
I have updated the README, thanks for point this out.

**Comment by haotianteng** [comment]
Okay, so it seems there is some issue with python 2.7 I will try to fix it, but if it's possible you can use python 3.6. Thanks

**Comment by haotianteng** [comment]
Problem solved, so now it should be fine to install by
```
pip install -r requirement.txt
```
or
```
python setup.py install
```
