### ISSUE TITLE
Error when training model using raw signals

### ISSUE THREAD

**Issue by ardakdemir** [haotianteng/Chiron#89]
I am trying to reproduce the results obtained by training a model on the same dataset with .signal and .label files. When I run the code I get the following error related to tensorflow:

Traceback (most recent call last):
  File "chiron/chiron_rcnn_train.py", line 229, in <module>
    run(args)
  File "chiron/chiron_rcnn_train.py", line 176, in run
    train()
  File "chiron/chiron_rcnn_train.py", line 80, in train
    net = compile_train_graph(config,FLAGS)
  File "chiron/chiron_rcnn_train.py", line 58, in compile_train_graph
    net.error,net.errors,net.y_ = model.prediction(net.logits, net.seq_length, net.y)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 439, in __iter__
    "Tensor objects are not iterable when eager execution is not "

python version : 2.7.12
tensorflow version : 1.8.0

**Comment by haotianteng** [comment]
Yes, the current version of Chiron use the TFRECORD format, instead of the original .signal and .label format. If you want to reproduce the result, use chiron v0.3 and tf-0.1.

**Comment by ardakdemir** [comment]
Thanks a lot for your quick reply.

Is there a way to generate the tfrecords from the .signal and .label files rather than the fasta files?
