### ISSUE TITLE
Not able to run on centos

### ISSUE THREAD

**Issue by lab-rat-kid** [haotianteng/Chiron#98]
I have tried running on centos and get the following:

`Traceback (most recent call last):
  File "/export/home/2141180e/downloads/anaconda3/bin/chiron", line 11, in <module>
    load_entry_point('chiron==0.5.1', 'console_scripts', 'chiron')()
  File "/export/home/2141180e/downloads/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/export/home/2141180e/downloads/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/export/home/2141180e/downloads/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/export/home/2141180e/downloads/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/export/home/2141180e/downloads/anaconda3/lib/python3.7/site-packages/chiron-0.5.1-py3.7.egg/chiron/entry.py", line 13, in <module>
    from chiron import chiron_eval
  File "/export/home/2141180e/downloads/anaconda3/lib/python3.7/site-packages/chiron-0.5.1-py3.7.egg/chiron/chiron_eval.py", line 19, in <module>
    from chiron import chiron_model
  File "/export/home/2141180e/downloads/anaconda3/lib/python3.7/site-packages/chiron-0.5.1-py3.7.egg/chiron/chiron_model.py", line 17, in <module>
    from chiron.rnn import rnn_layers
  File "/export/home/2141180e/downloads/anaconda3/lib/python3.7/site-packages/chiron-0.5.1-py3.7.egg/chiron/rnn.py", line 14, in <module>
    from tensorflow.contrib.rnn import LSTMCell
ModuleNotFoundError: No module named 'tensorflow.contrib'`

**Comment by lab-rat-kid** [comment]
needs tensorflow ==1.15
